all:
  hosts:
    '192.168.107.120':
    '192.168.107.174':
    '192.168.107.163':
    '192.168.107.29':
    '192.168.107.225':
    '192.168.107.103':
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://homeassistant.local:1883
        mqttOptions:
          username: room-assistant
          password: room-assistant-password
      bluetoothClassic:
        addresses:
          - 'aa:27:14:dc:ba:fc'
        hciDeviceId: 0
      bluetoothLowEnergy:
	timeout: 60
	allowlist:
	  - 0592CCE7-ECA8-415B-9E41-A4886DE04214
	hciDeviceId: 1

