all:
  hosts:
    '192.168.107.120':
      ansible_user: pi
      ansible_password: festal.between.blissful.office
    '192.168.107.174':
      ansible_user: pi
      ansible_password: festal.between.blissful.livingroom
    '192.168.107.163':
      ansible_user: pi
      ansible_password: festal.between.blissful.kitchen
    '192.168.107.29':
      ansible_user: pi
      ansible_password: festal.between.blissful.hallway
    '192.168.107.225':
      ansible_user: pi
      ansible_password: festal.between.blissful.guestbedroom
    '192.168.107.103':
      ansible_user: pi
      ansible_password: festal.between.blissful.bedroom
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://192.168.0.32:1883
        mqttOptions:
          username: room-assistant
          password: room-assistant-password
      bluetoothClassic:
        addresses:
          - 'aa:27:14:dc:ba:fc'
        hciDeviceId: 0
      bluetoothLowEnergy:
        timeout: 60
        allowlist:
          - 0592CCE7-ECA8-415B-9E41-A4886DE04214
          - D5FE9906-4E1D-4C05-AE32-62DDDA140688
        hciDeviceId: 1
      cluster:
        networkInterface: wlan0
        port: 6425
        peerAddresses:
          - 192.168.107.103:6425
          - 192.168.107.225:6425
          - 192.168.107.29:6425
          - 192.168.107.120:6425
          - 192.168.107.163:6425
          - 192.168.107.174:6425
        autoDiscovery: false

